### ISSUE TITLE
LWT not working when closing the app on the phone

### ISSUE THREAD

**Issue by toddor** [ckrey/MQTTChat#1]
It works only when I close the app through xcode. By not working I mean, the broker knows the phone is disconnected but doesn't publish the offline msg

**Comment by ckrey** [comment]
@toddor when you terminate the app (by hitting the Home key), it sends an MQTT DISCONNECT, which gracefully terminates the session to the broker. In this case the server does not send an LWT.
If you kill the app by stopping it via Xcode, it does not send a DISCONNECT and the broker correctly sends an LWT.

> 3.1.2.5 Will Flag
> 
> Position: bit 2 of the Connect Flags.
> 
> If the Will Flag is set to 1 this indicates that, if the Connect request is accepted, a Will Message
> MUST be stored on the Server and associated with the Network Connection. The Will Message
> MUST be published when the Network Connection is subsequently closed unless the Will Message
> has been deleted by the Server on receipt of a DISCONNECT Packet [MQTT-3.1.2-8].
> Situations in which the Will Message is published include, but are not limited to:
> An I/O error or network failure detected by the Server.
> The Client fails to communicate within the Keep Alive time.
> The Client closes the Network Connection without first sending a DISCONNECT Packet.
> The Server closes the Network Connection because of a protocol error.

Quoting from http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html

**Comment by toddor** [comment]
Thank you @ckrey ! It was my misunderstanding.

**Comment by bfruiz04** [comment]
hi friend nice work !! i am getting the error 
ld: library not found for -lCocoaLumberjack
have you idea about the reason? thanks!

**Comment by ckrey** [comment]
you need to open the .xcworkspace file, not the .xcproject
