### ISSUE TITLE
gets called when a published message was fail

### ISSUE THREAD

**Issue by steve-four** [ckrey/MQTTChat#3]
MQTTSessionManager 

/*\* gets called when a published message was actually delivered
 @param msgID the Message Identifier of the delivered message
 @note this method is called after a publish with qos 1 or 2 only
 */
- (void)messageDelivered:(UInt16)msgID;

add method to gets called when a published message was fail,

**Comment by ckrey** [comment]
MQTTSessionManager will try to repeat to publish in QoS1 or QoS2 until it is acknowledged. 
Thus it will not fail until you give up.

You may check / observe .state to see if MQTTSessionManager is currently connected or not.

Other than that, please see my comments on #4
