### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by wutingyu** [ckrey/MQTTChat#4]
hey ckrey
Sorry，myEnglish is awful！
please  help! When I connect to host or resovle message, I should use MqttSession or MqttSessionManager?  I find they may have the same function！ Choose one of them？
Could you tell me what's the difference between them two?

**Comment by ckrey** [comment]
MQTTSessionManager deals with re-connects and re-subscribes and the automatic closing / opening of sessions when the app goes to background / is reactivated.

MQTTSessionManager uses MQTTSession.

For a simple application, you may use MQTTSessionManager or subclass it.
If you want to have full control, use MQTTSession.

**Comment by ckrey** [comment]
Please put further questions / issues to https://github.com/ckrey/MQTT-Client-Framework

MQTTChat is just a simple demo app
