### ISSUE TITLE
Not able to configure the application in my system

### ISSUE THREAD

**Issue by Vkagde** [ckrey/MQTTChat#6]
Showing All Messages
  "_OBJC_CLASS_$_MQTTSessionManager", referenced from:
 symbol(s) not found for architecture armv7
gettting link error

**Comment by ckrey** [comment]
As MQTTChat is only a demonstration iOS App for [MQTT-Client-Framework](https://github.com/ckrey/MQTT-Client-Framework)

For all documentation, issues, etc. please refer to the MQTT-Client-Framework
